global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'tap-service'
    static_configs:
      - targets: ['tap-service:3200']

  - job_name: 'deepgram-gw'
    static_configs:
      - targets: ['deepgram-gw:8080']

  - job_name: 'mti-gw'
    static_configs:
      - targets: ['192.168.1.65:9093']
